# Generated by Django 5.1.4 on 2024-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name=30)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('appointment_date', models.DateField()),
            ],
        ),
    ]
