# Generated by Django 5.1.4 on 2024-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
