# Generated by Django 5.1.4 on 2024-12-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_appointment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name=30)),
                ('phone', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=7)),
                ('Message', models.TextField()),
            ],
        ),
    ]
