# Generated by Django 5.1.4 on 2024-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_inquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiry',
            new_name='Contact',
        ),
    ]
