# Generated by Django 5.1.4 on 2024-12-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_departments_services_appointment_application_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
