# Generated by Django 5.0.7 on 2024-12-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_phone_appointment_age_alter_appointment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
