# Generated by Django 5.0.7 on 2024-12-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
