# Generated by Django 5.0.7 on 2024-12-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_contact_email_alter_contact_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Service',
        ),
    ]
