# Generated by Django 5.0.7 on 2024-12-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
